apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pet-deploy
  name: novu-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pet-deploy
  template:
    metadata:
      labels:
        app: pet-deploy
    spec:
      containers:
      - image: novu123/takin:latest
        name: pet
